<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="nl" xml:lang="nl"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Wat weten we eigenlijk over de doelen van het Rijk?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="dashboard_files/libs/clipboard/clipboard.min.js"></script>
<script src="dashboard_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="dashboard_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="dashboard_files/libs/quarto-html/popper.min.js"></script>
<script src="dashboard_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="dashboard_files/libs/quarto-html/anchor.min.js"></script>
<link href="dashboard_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="dashboard_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="dashboard_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="dashboard_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="dashboard_files/libs/bootstrap/bootstrap-dd7c7592e76f6f77893656537ffebd10.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Thema’s</h2>
   
  <ul>
  <li><a href="#leeswijzer" id="toc-leeswijzer" class="nav-link active" data-scroll-target="#leeswijzer">Leeswijzer</a></li>
  <li><a href="#indicatoren-met-een-becijferd-doel" id="toc-indicatoren-met-een-becijferd-doel" class="nav-link" data-scroll-target="#indicatoren-met-een-becijferd-doel">Indicatoren met een becijferd doel</a></li>
  <li><a href="#indicatoren-zonder-becijferd-doel" id="toc-indicatoren-zonder-becijferd-doel" class="nav-link" data-scroll-target="#indicatoren-zonder-becijferd-doel">Indicatoren zonder becijferd doel</a></li>
  <li><a href="#waar-het-misgaat" id="toc-waar-het-misgaat" class="nav-link" data-scroll-target="#waar-het-misgaat">Waar het misgaat</a></li>
  <li><a href="#hoe-hard-zijn-de-doelen" id="toc-hoe-hard-zijn-de-doelen" class="nav-link" data-scroll-target="#hoe-hard-zijn-de-doelen">Hoe hard zijn de doelen?</a></li>
  <li><a href="#bestaanszekerheid" id="toc-bestaanszekerheid" class="nav-link" data-scroll-target="#bestaanszekerheid">Bestaanszekerheid</a></li>
  <li><a href="#binnenlandse-veiligheid" id="toc-binnenlandse-veiligheid" class="nav-link" data-scroll-target="#binnenlandse-veiligheid">Binnenlandse Veiligheid</a></li>
  <li><a href="#defensie-en-ontwikkelingssamenwerking" id="toc-defensie-en-ontwikkelingssamenwerking" class="nav-link" data-scroll-target="#defensie-en-ontwikkelingssamenwerking">Defensie en Ontwikkelingssamenwerking</a></li>
  <li><a href="#economie-arbeidsmarkt" id="toc-economie-arbeidsmarkt" class="nav-link" data-scroll-target="#economie-arbeidsmarkt">Economie &amp; Arbeidsmarkt</a></li>
  <li><a href="#gelijkheidnon-discriminatie" id="toc-gelijkheidnon-discriminatie" class="nav-link" data-scroll-target="#gelijkheidnon-discriminatie">Gelijkheid/non-discriminatie</a></li>
  <li><a href="#kennis-vaardigheden" id="toc-kennis-vaardigheden" class="nav-link" data-scroll-target="#kennis-vaardigheden">Kennis &amp; Vaardigheden</a></li>
  <li><a href="#klimaat-en-milieu" id="toc-klimaat-en-milieu" class="nav-link" data-scroll-target="#klimaat-en-milieu">Klimaat en Milieu</a></li>
  <li><a href="#overheidsfinanciën-openbaar-bestuur" id="toc-overheidsfinanciën-openbaar-bestuur" class="nav-link" data-scroll-target="#overheidsfinanciën-openbaar-bestuur">Overheidsfinanciën &amp; Openbaar bestuur</a></li>
  <li><a href="#wonen" id="toc-wonen" class="nav-link" data-scroll-target="#wonen">Wonen</a></li>
  <li><a href="#zorg" id="toc-zorg" class="nav-link" data-scroll-target="#zorg">Zorg</a></li>
  <li><a href="#alle-indicatoren" id="toc-alle-indicatoren" class="nav-link" data-scroll-target="#alle-indicatoren">Alle indicatoren</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Wat weten we eigenlijk over de doelen van het Rijk?</h1>
<p class="subtitle lead">71 indicatoren uit Blik op Nederland, met de trend doorgetrokken waar dat kan</p>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="leeswijzer" class="level2">
<h2 class="anchored" data-anchor-id="leeswijzer">Leeswijzer</h2>
<p>Deze pagina neemt de indicatoren van de Algemene Rekenkamer en beantwoordt er één vraag bij: <strong>halen we het doel, of niet?</strong></p>
<p>Het originele dashboard toont een lijn en een doel naast elkaar, maar laat het daarbij. Hier is de lijn doorgetrokken, op drie manieren:</p>
<ul>
<li>waar de dataset van de Rekenkamer zelf te kort is, is de reeks verlengd met cijfers van het <strong>CBS</strong>, die als de recentste cijfers gelden waar ze de Rekenkamer-data overlappen;</li>
<li>waar het <strong>CPB</strong> een officiële raming publiceert, is die toegevoegd als groene stippellijn — de kortetermijnraming (cMEV) voor de eerstkomende jaren, de middellangetermijnverkenning (MLT) voor de jaren daarna;</li>
<li>waar geen van beide een cijfer geeft, is de trend van de laatste jaren doorgerekend.</li>
</ul>
<p><strong>Wat de kleuren betekenen</strong> staat in de legenda hieronder. Kort: groen is goed nieuws, geel is te langzaam, rood is de verkeerde kant op. Grijs betekent dat er geen doel bekend is om tegen af te zetten — dat geldt voor meer dan de helft van de indicatoren, en dat is zelf al een uitkomst.</p>
<p><strong>Onder elke grafiek</strong> staat in één zin wat er aan de hand is: of het doel gehaald wordt, en zo niet, hoe snel de indicator beweegt.</p>
<p class="lead">
Van de 71 indicatoren heeft er 25 een streefwaarde waaraan je kunt aflezen of het doel gehaald wordt. Bij 43 staat alleen welke kant het op moet, en bij 3 staat ook dat niet. Voor 8 indicatoren heeft de coalitie zich aan een eigen doel verbonden.
</p>
<p>Dat is op zichzelf de eerste uitkomst. Voortgang meten kan alleen waar een doel becijferd is; voor de rest blijft het bij de vraag of een indicator de gewenste kant op beweegt. Hieronder staat eerst de kleine groep waar een echt oordeel mogelijk is, daarna de rest.</p>
<div class="legenda">
<p><span><i class="stip s-gehaald"></i>Doel gehaald</span> <span><i class="stip s-koers"></i>Op koers</span> <span><i class="stip s-traag"></i>Te traag</span> <span><i class="stip s-mis"></i>Verkeerde richting</span> <span><i class="stip s-geen"></i>Alleen een richting bekend</span> <span><i class="stip s-onbekend"></i>Geen richting bekend</span></p>
</div>
<p>De onderbroken lijn in een grafiek is de streefwaarde. Waar een tweede, lichtere stippellijn staat, geldt naast de gehanteerde norm nog een ander doel — bij R&amp;D-uitgaven bijvoorbeeld de EU-doelstelling van 3% naast het Nederlandse doel van 2,5%.</p>
</section>
<section id="indicatoren-met-een-becijferd-doel" class="level2">
<h2 class="anchored" data-anchor-id="indicatoren-met-een-becijferd-doel">Indicatoren met een becijferd doel</h2>
<div class="koersraster">
<div class="kaart">
<div class="thema">
Bestaanszekerheid
</div>
<div class="naam">
% personen onder NL-armoedegrens (nieuwe CBS–SCP–Nibud-methode)
</div>
<div class="cijfer">
3,1<span class="eenheid"></span>
</div>
<img src="figuren/percent_personen_onder_nl_armoedegrens_nieuwe_cbs_scp_nibud_methode.svg" alt="Verloop van % personen onder NL-armoedegrens (nieuwe CBS–SCP–Nibud-methode)">
<div class="oordeel">
<i class="stip s-gehaald"></i>Voldoet aan de norm
</div>
</div>
<div class="kaart">
<div class="thema">
Bestaanszekerheid
</div>
<div class="naam">
Kinderarmoede (% kinderen &lt; 18)
</div>
<div class="cijfer">
2,8<span class="eenheid">% kinderen &lt; 18</span>
</div>
<img src="figuren/kinderarmoede_percent_kinderen_18.svg" alt="Verloop van Kinderarmoede (% kinderen < 18)">
<div class="oordeel">
<i class="stip s-gehaald"></i>Voldoet aan de norm
</div>
</div>
<div class="kaart">
<div class="thema">
Defensie en Ontwikkelingssamenwerking
</div>
<div class="naam">
Investeringsquote defensie uitgaven (% defensie-uitgaven voor investeringen)
</div>
<div class="cijfer">
30,1<span class="eenheid"></span>
</div>
<img src="figuren/investeringsquote_defensie_uitgaven_percent_defensie_uitgaven_voor_investeringen.svg" alt="Verloop van Investeringsquote defensie uitgaven (% defensie-uitgaven voor investeringen)">
<div class="oordeel">
<i class="stip s-gehaald"></i>Voldoet aan de norm
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur · CBS-reeks
</div>
<div class="naam">
EMU-saldo (% BBP)
</div>
<div class="cijfer">
-1,6<span class="eenheid">% BBP</span>
</div>
<img src="figuren/emu_saldo_percent_bbp.svg" alt="Verloop van EMU-saldo (% BBP)">
<div class="oordeel">
<i class="stip s-gehaald"></i>Voldoet aan de norm
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur · CBS-reeks
</div>
<div class="naam">
EMU-schuld (% BBP)
</div>
<div class="cijfer">
44,7<span class="eenheid">% BBP</span>
</div>
<img src="figuren/emu_schuld_percent_bbp.svg" alt="Verloop van EMU-schuld (% BBP)">
<div class="oordeel">
<i class="stip s-gehaald"></i>Voldoet aan de norm
</div>
</div>
<div class="kaart">
<div class="thema">
Defensie en Ontwikkelingssamenwerking
</div>
<div class="naam">
Defensie uitgaven (NAVO-norm)
</div>
<div class="cijfer">
2,2<span class="eenheid">NAVO-norm</span>
</div>
<img src="figuren/defensie_uitgaven_navo_norm.svg" alt="Verloop van Defensie uitgaven (NAVO-norm)">
<div class="oordeel">
<i class="stip s-koers"></i>Op koers voor 2035
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Ammoniak-uitstoot (NH3) (industrie)
</div>
<div class="cijfer">
1,0<span class="eenheid">industrie</span>
</div>
<img src="figuren/ammoniak_uitstoot_nh3_industrie.svg" alt="Verloop van Ammoniak-uitstoot (NH3) (industrie)">
<div class="oordeel">
<i class="stip s-koers"></i>Op koers voor 2035
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Ammoniak-uitstoot (NH3) (landbouw)
</div>
<div class="cijfer">
94,9<span class="eenheid">landbouw</span>
</div>
<img src="figuren/ammoniak_uitstoot_nh3_landbouw.svg" alt="Verloop van Ammoniak-uitstoot (NH3) (landbouw)">
<div class="oordeel">
<i class="stip s-koers"></i>Op koers voor 2035
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
NOx-uistoot (mobiliteit)
</div>
<div class="cijfer">
122,4<span class="eenheid">mobiliteit</span>
</div>
<img src="figuren/n_ox_uistoot_mobiliteit.svg" alt="Verloop van NOx-uistoot (mobiliteit)">
<div class="oordeel">
<i class="stip s-koers"></i>Op koers voor 2035
</div>
</div>
<div class="kaart">
<div class="thema">
Defensie en Ontwikkelingssamenwerking
</div>
<div class="naam">
Uitgaven ontwikkelingssamenwerking (als % BNI)
</div>
<div class="cijfer">
0,5<span class="eenheid">als % BNI</span>
</div>
<img src="figuren/uitgaven_ontwikkelingssamenwerking_als_percent_bni.svg" alt="Verloop van Uitgaven ontwikkelingssamenwerking (als % BNI)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — beweegt nauwelijks
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt · CBS-reeks
</div>
<div class="naam">
R en D uitgaven (% BBP)
</div>
<div class="cijfer">
2,4<span class="eenheid">% BBP</span>
</div>
<img src="figuren/r_en_d_uitgaven_percent_bbp.svg" alt="Verloop van R en D uitgaven (% BBP)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — stijgt met 0,02 % BBP per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Aandeel Natura 2000 dat voldoende onder de Kritische DepositieWaarde (KDW) zit
</div>
<div class="cijfer">
29,9<span class="eenheid"></span>
</div>
<img src="figuren/aandeel_natura_2000_dat_voldoende_onder_de_kritische_depositie_waarde_kdw_zit.svg" alt="Verloop van Aandeel Natura 2000 dat voldoende onder de Kritische DepositieWaarde (KDW) zit">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — stijgt met 0,21 per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Broeikasgasemissies (CO2-eq. Mton)
</div>
<div class="cijfer">
145,6<span class="eenheid">CO2-eq. Mton</span>
</div>
<img src="figuren/broeikasgasemissies_co2_eq_mton.svg" alt="Verloop van Broeikasgasemissies (CO2-eq. Mton)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — daalt met 5,71 CO2-eq. Mton per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Hernieuwbare energie - eindgebruik (%)
</div>
<div class="cijfer">
20,2<span class="eenheid">%</span>
</div>
<img src="figuren/hernieuwbare_energie_eindgebruik_percent.svg" alt="Verloop van Hernieuwbare energie - eindgebruik (%)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — stijgt met 2,19 % per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Stikstofdepositie gevoelige natuurgebieden (mol/ha)
</div>
<div class="cijfer">
1.348,0<span class="eenheid">mol/ha</span>
</div>
<img src="figuren/stikstofdepositie_gevoelige_natuurgebieden_mol_ha.svg" alt="Verloop van Stikstofdepositie gevoelige natuurgebieden (mol/ha)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — daalt met 18,97 mol/ha per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
Dakloosheid (dakloze mensen x 1.000)
</div>
<div class="cijfer">
33,0<span class="eenheid">dakloze mensen x 1.000</span>
</div>
<img src="figuren/dakloosheid_dakloze_mensen_x_1_000.svg" alt="Verloop van Dakloosheid (dakloze mensen x 1.000)">
<div class="oordeel">
<i class="stip s-traag"></i>Te traag — daalt met 0,82 dakloze mensen x 1.000 per jaar
</div>
</div>
<div class="kaart">
<div class="thema">
Defensie en Ontwikkelingssamenwerking
</div>
<div class="naam">
Vullingsgraad formatie krijgsmacht (Militair personeel)
</div>
<div class="cijfer">
79,5<span class="eenheid">Militair personeel</span>
</div>
<img src="figuren/vullingsgraad_formatie_krijgsmacht_militair_personeel.svg" alt="Verloop van Vullingsgraad formatie krijgsmacht (Militair personeel)">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
Aantallen vroegtijdig schoolverlaters (12-23 jaar)
</div>
<div class="cijfer">
34.210,0<span class="eenheid">12-23 jaar</span>
</div>
<img src="figuren/aantallen_vroegtijdig_schoolverlaters_12_23_jaar.svg" alt="Verloop van Aantallen vroegtijdig schoolverlaters (12-23 jaar)">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
% rokers 12-18 jr.
</div>
<div class="cijfer">
7,9<span class="eenheid"></span>
</div>
<img src="figuren/percent_rokers_12_18_jr.svg" alt="Verloop van % rokers 12-18 jr.">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties BMR)
</div>
<div class="cijfer">
88,8<span class="eenheid"></span>
</div>
<img src="figuren/vaccinatiegraad_rijksvaccinatieprogramma_zuigelingen_geregistreerde_vaccinaties_bmr.svg" alt="Verloop van Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties BMR)">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties totaal)
</div>
<div class="cijfer">
86,0<span class="eenheid"></span>
</div>
<img src="figuren/vaccinatiegraad_rijksvaccinatieprogramma_zuigelingen_geregistreerde_vaccinaties_totaal.svg" alt="Verloop van Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties totaal)">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Voldoende beweging (% bevolking &gt; 4 jr.)
</div>
<div class="cijfer">
47,0<span class="eenheid">% bevolking &gt; 4 jr.</span>
</div>
<img src="figuren/voldoende_beweging_percent_bevolking_4_jr.svg" alt="Verloop van Voldoende beweging (% bevolking > 4 jr.)">
<div class="oordeel">
<i class="stip s-mis"></i>Beweegt van het doel af
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
Minimaal digitale basisvaardigheden (% personen &gt; 12 jaar)
</div>
<div class="cijfer">
78,7<span class="eenheid">% personen &gt; 12 jaar</span>
</div>
<img src="figuren/minimaal_digitale_basisvaardigheden_percent_personen_12_jaar.svg" alt="Verloop van Minimaal digitale basisvaardigheden (% personen > 12 jaar)">
<div class="oordeel">
<i class="stip s-onbekend"></i>Te weinig data
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Kwaliteit oppervlaktewater (biologisch) (% van goede kwaliteit))
</div>
<div class="cijfer">
14,6<span class="eenheid"></span>
</div>
<img src="figuren/kwaliteit_oppervlaktewater_biologisch_percent_van_goede_kwaliteit.svg" alt="Verloop van Kwaliteit oppervlaktewater (biologisch) (% van goede kwaliteit))">
<div class="oordeel">
<i class="stip s-onbekend"></i>Te weinig data
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Kwaliteit oppervlaktewater (chemisch) (% van voldoende kwaliteit))
</div>
<div class="cijfer">
0,7<span class="eenheid"></span>
</div>
<img src="figuren/kwaliteit_oppervlaktewater_chemisch_percent_van_voldoende_kwaliteit.svg" alt="Verloop van Kwaliteit oppervlaktewater (chemisch) (% van voldoende kwaliteit))">
<div class="oordeel">
<i class="stip s-onbekend"></i>Te weinig data
</div>
</div>
</div>
</section>
<section id="indicatoren-zonder-becijferd-doel" class="level2">
<h2 class="anchored" data-anchor-id="indicatoren-zonder-becijferd-doel">Indicatoren zonder becijferd doel</h2>
<p>Hier valt geen voortgang te meten, alleen beweging. De onderbroken doellijn ontbreekt dan ook.</p>
<div class="koersraster">
<div class="kaart">
<div class="thema">
Bestaanszekerheid
</div>
<div class="naam">
Armoede intensiteit (% inkomenstekort ten opzichte van de armoedegrens bij de mediaan binnen de groep in armoede)
</div>
<div class="cijfer">
19,0<span class="eenheid"></span>
</div>
<img src="figuren/armoede_intensiteit_percent_inkomenstekort_ten_opzichte_van_de_armoedegrens_bij_de_mediaan_binnen_de_groep_in_armoede.svg" alt="Verloop van Armoede intensiteit (% inkomenstekort ten opzichte van de armoedegrens bij de mediaan binnen de groep in armoede)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Bestaanszekerheid
</div>
<div class="naam">
Huishoudens met problematische schulden (%)
</div>
<div class="cijfer">
8,6<span class="eenheid">%</span>
</div>
<img src="figuren/huishoudens_met_problematische_schulden_percent.svg" alt="Verloop van Huishoudens met problematische schulden (%)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
Aantal geregistreerde misdrijven
</div>
<div class="cijfer">
816,0<span class="eenheid"></span>
</div>
<img src="figuren/aantal_geregistreerde_misdrijven.svg" alt="Verloop van Aantal geregistreerde misdrijven">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
Aantal opgehelderde misdrijven
</div>
<div class="cijfer">
180,0<span class="eenheid"></span>
</div>
<img src="figuren/aantal_opgehelderde_misdrijven.svg" alt="Verloop van Aantal opgehelderde misdrijven">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
High Impact Crimes x 1.000
</div>
<div class="cijfer">
103,7<span class="eenheid"></span>
</div>
<img src="figuren/high_impact_crimes_x_1_000.svg" alt="Verloop van High Impact Crimes x 1.000">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
National Cybersecurity Index - NL (ranking)
</div>
<div class="cijfer">
35,0<span class="eenheid">ranking</span>
</div>
<img src="figuren/national_cybersecurity_index_nl_ranking.svg" alt="Verloop van National Cybersecurity Index - NL (ranking)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
National Cybersecurity Index - NL (score)
</div>
<div class="cijfer">
81,7<span class="eenheid">score</span>
</div>
<img src="figuren/national_cybersecurity_index_nl_score.svg" alt="Verloop van National Cybersecurity Index - NL (score)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
Ophelderingspercentage misdrijven
</div>
<div class="cijfer">
22,1<span class="eenheid"></span>
</div>
<img src="figuren/ophelderingspercentage_misdrijven.svg" alt="Verloop van Ophelderingspercentage misdrijven">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
Slachtoffers traditionele criminaliteit (% bevolking)
</div>
<div class="cijfer">
20,0<span class="eenheid">% bevolking</span>
</div>
<img src="figuren/slachtoffers_traditionele_criminaliteit_percent_bevolking.svg" alt="Verloop van Slachtoffers traditionele criminaliteit (% bevolking)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Binnenlandse Veiligheid
</div>
<div class="naam">
Slachtoffers van moord en doodslag per 100.000 inwoners
</div>
<div class="cijfer">
0,7<span class="eenheid"></span>
</div>
<img src="figuren/slachtoffers_van_moord_en_doodslag_per_100_000_inwoners.svg" alt="Verloop van Slachtoffers van moord en doodslag per 100.000 inwoners">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt
</div>
<div class="naam">
Arbeidsproductiviteit (toegevoegde waarde per gewerkt uur; index, 2021 = 100)
</div>
<div class="cijfer">
99,9<span class="eenheid"></span>
</div>
<img src="figuren/arbeidsproductiviteit_toegevoegde_waarde_per_gewerkt_uur_index_2021_100.svg" alt="Verloop van Arbeidsproductiviteit (toegevoegde waarde per gewerkt uur; index, 2021 = 100)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt
</div>
<div class="naam">
BBP reële groei
</div>
<div class="cijfer">
1,1<span class="eenheid"></span>
</div>
<img src="figuren/bbp_reele_groei.svg" alt="Verloop van BBP reële groei">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt
</div>
<div class="naam">
Concurrentiekracht (World Competitiveness Ranking); rang NL binnen Europa
</div>
<div class="cijfer">
5,0<span class="eenheid"></span>
</div>
<img src="figuren/concurrentiekracht_world_competitiveness_ranking_rang_nl_binnen_europa.svg" alt="Verloop van Concurrentiekracht (World Competitiveness Ranking); rang NL binnen Europa">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt
</div>
<div class="naam">
Netto arbeidsparticipatie (% 15-75-jarigen met betaald werk)
</div>
<div class="cijfer">
73,2<span class="eenheid"></span>
</div>
<img src="figuren/netto_arbeidsparticipatie_percent_15_75_jarigen_met_betaald_werk.svg" alt="Verloop van Netto arbeidsparticipatie (% 15-75-jarigen met betaald werk)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Economie &amp; Arbeidsmarkt
</div>
<div class="naam">
Werkloosheid (% werkzoekenden 15-75 jaar die direct beschikbaar zijn als percentage van beroepsbevolking)
</div>
<div class="cijfer">
3,9<span class="eenheid"></span>
</div>
<img src="figuren/werkloosheid_percent_werkzoekenden_15_75_jaar_die_direct_beschikbaar_zijn_als_percentage_van_beroepsbevolking.svg" alt="Verloop van Werkloosheid (% werkzoekenden 15-75 jaar die direct beschikbaar zijn als percentage van beroepsbevolking)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Ervaren discriminatie (% personen 15+)
</div>
<div class="cijfer">
12,0<span class="eenheid">% personen 15+</span>
</div>
<img src="figuren/ervaren_discriminatie_percent_personen_15.svg" alt="Verloop van Ervaren discriminatie (% personen 15+)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Gender-equality index (rang)
</div>
<div class="cijfer">
5,0<span class="eenheid">rang</span>
</div>
<img src="figuren/gender_equality_index_rang.svg" alt="Verloop van Gender-equality index (rang)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Gender-equality index (score)
</div>
<div class="cijfer">
69,5<span class="eenheid">score</span>
</div>
<img src="figuren/gender_equality_index_score.svg" alt="Verloop van Gender-equality index (score)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Inkomensongelijkheid (Gini-coëfficiënt)
</div>
<div class="cijfer">
0,3<span class="eenheid">Gini-coëfficiënt</span>
</div>
<img src="figuren/inkomensongelijkheid_gini_coefficient.svg" alt="Verloop van Inkomensongelijkheid (Gini-coëfficiënt)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Loonkloof man/vrouw (inkomen vrouwen als % van inkomen mannen)
</div>
<div class="cijfer">
90,3<span class="eenheid"></span>
</div>
<img src="figuren/loonkloof_man_vrouw_inkomen_vrouwen_als_percent_van_inkomen_mannen.svg" alt="Verloop van Loonkloof man/vrouw (inkomen vrouwen als % van inkomen mannen)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Vermogensongelijkheid (Gini-coëfficiënt)
</div>
<div class="cijfer">
0,7<span class="eenheid">Gini-coëfficiënt</span>
</div>
<img src="figuren/vermogensongelijkheid_gini_coefficient.svg" alt="Verloop van Vermogensongelijkheid (Gini-coëfficiënt)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (mannen)
</div>
<div class="cijfer">
20,8<span class="eenheid">mannen</span>
</div>
<img src="figuren/verschil_in_jaren_gezonde_levensverwachting_tussen_hoogste_en_laagste_inkomenskwintiel_mannen.svg" alt="Verloop van Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (mannen)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Gelijkheid/non-discriminatie
</div>
<div class="naam">
Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (vrouwen)
</div>
<div class="cijfer">
21,7<span class="eenheid">vrouwen</span>
</div>
<img src="figuren/verschil_in_jaren_gezonde_levensverwachting_tussen_hoogste_en_laagste_inkomenskwintiel_vrouwen.svg" alt="Verloop van Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (vrouwen)">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PIAAC-scores probleemoplossend vermogen
</div>
<div class="cijfer">
265,0<span class="eenheid"></span>
</div>
<img src="figuren/piaac_scores_probleemoplossend_vermogen.svg" alt="Verloop van PIAAC-scores probleemoplossend vermogen">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PIAAC-scores rekenvaardigheid
</div>
<div class="cijfer">
284,0<span class="eenheid"></span>
</div>
<img src="figuren/piaac_scores_rekenvaardigheid.svg" alt="Verloop van PIAAC-scores rekenvaardigheid">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PIAAC-scores taalvaardigheid
</div>
<div class="cijfer">
279,0<span class="eenheid"></span>
</div>
<img src="figuren/piaac_scores_taalvaardigheid.svg" alt="Verloop van PIAAC-scores taalvaardigheid">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PISA-scores lezen
</div>
<div class="cijfer">
459,0<span class="eenheid"></span>
</div>
<img src="figuren/pisa_scores_lezen.svg" alt="Verloop van PISA-scores lezen">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PISA-scores science
</div>
<div class="cijfer">
488,0<span class="eenheid"></span>
</div>
<img src="figuren/pisa_scores_science.svg" alt="Verloop van PISA-scores science">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Kennis &amp; Vaardigheden
</div>
<div class="naam">
PISA-scores wiskunde
</div>
<div class="cijfer">
493,0<span class="eenheid"></span>
</div>
<img src="figuren/pisa_scores_wiskunde.svg" alt="Verloop van PISA-scores wiskunde">
<div class="oordeel">
<i class="stip s-geen"></i>Alleen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Living Planet Index - NL (fauna het land) (1990 = 100)
</div>
<div class="cijfer">
69,0<span class="eenheid">1990 = 100</span>
</div>
<img src="figuren/living_planet_index_nl_fauna_het_land_1990_100.svg" alt="Verloop van Living Planet Index - NL (fauna het land) (1990 = 100)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Klimaat en Milieu
</div>
<div class="naam">
Living Planet Index - NL (fauna zoetwater)
</div>
<div class="cijfer">
159,0<span class="eenheid">fauna zoetwater</span>
</div>
<img src="figuren/living_planet_index_nl_fauna_zoetwater.svg" alt="Verloop van Living Planet Index - NL (fauna zoetwater)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur
</div>
<div class="naam">
"Rule of Law"-index (rang)
</div>
<div class="cijfer">
9,0<span class="eenheid">rang</span>
</div>
<img src="figuren/rule_of_law_index_rang.svg" alt="Verloop van &quot;Rule of Law&quot;-index (rang)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur
</div>
<div class="naam">
"Rule of Law"-index (score)
</div>
<div class="cijfer">
0,8<span class="eenheid">score</span>
</div>
<img src="figuren/rule_of_law_index_score.svg" alt="Verloop van &quot;Rule of Law&quot;-index (score)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur
</div>
<div class="naam">
EMU-saldo (€ mld)
</div>
<div class="cijfer">
-18,7<span class="eenheid">€ mld</span>
</div>
<img src="figuren/emu_saldo_mld.svg" alt="Verloop van EMU-saldo (€ mld)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur
</div>
<div class="naam">
Totale overheidsuitgaven als % BBP
</div>
<div class="cijfer">
44,9<span class="eenheid"></span>
</div>
<img src="figuren/totale_overheidsuitgaven_als_percent_bbp.svg" alt="Verloop van Totale overheidsuitgaven als % BBP">
<div class="oordeel">
<i class="stip s-onbekend"></i>Geen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Overheidsfinanciën &amp; Openbaar bestuur
</div>
<div class="naam">
Vertrouwen in Tweede Kamer (% met (tamelijk) veel vertrouwen)
</div>
<div class="cijfer">
24,6<span class="eenheid"></span>
</div>
<img src="figuren/vertrouwen_in_tweede_kamer_percent_met_tamelijk_veel_vertrouwen.svg" alt="Verloop van Vertrouwen in Tweede Kamer (% met (tamelijk) veel vertrouwen)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
(Mediane) Woonquote (eigenaar)
</div>
<div class="cijfer">
17,1<span class="eenheid">eigenaar</span>
</div>
<img src="figuren/mediane_woonquote_eigenaar.svg" alt="Verloop van (Mediane) Woonquote (eigenaar)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
(Mediane) Woonquote (huurder)
</div>
<div class="cijfer">
26,4<span class="eenheid">huurder</span>
</div>
<img src="figuren/mediane_woonquote_huurder.svg" alt="Verloop van (Mediane) Woonquote (huurder)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
Verdeling woningvoorraad naar eigendom (koop)
</div>
<div class="cijfer">
4.754,0<span class="eenheid">koop</span>
</div>
<img src="figuren/verdeling_woningvoorraad_naar_eigendom_koop.svg" alt="Verloop van Verdeling woningvoorraad naar eigendom (koop)">
<div class="oordeel">
<i class="stip s-onbekend"></i>Geen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
Verdeling woningvoorraad naar eigendom (sociale huur)
</div>
<div class="cijfer">
2.332,0<span class="eenheid">sociale huur</span>
</div>
<img src="figuren/verdeling_woningvoorraad_naar_eigendom_sociale_huur.svg" alt="Verloop van Verdeling woningvoorraad naar eigendom (sociale huur)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
Verdeling woningvoorraad naar eigendom (vrije sectorhuur)
</div>
<div class="cijfer">
1.181,0<span class="eenheid">vrije sectorhuur</span>
</div>
<img src="figuren/verdeling_woningvoorraad_naar_eigendom_vrije_sectorhuur.svg" alt="Verloop van Verdeling woningvoorraad naar eigendom (vrije sectorhuur)">
<div class="oordeel">
<i class="stip s-onbekend"></i>Geen richting
</div>
</div>
<div class="kaart">
<div class="thema">
Wonen
</div>
<div class="naam">
Woningen tekort (aantal)
</div>
<div class="cijfer">
396,0<span class="eenheid">aantal</span>
</div>
<img src="figuren/woningen_tekort_aantal.svg" alt="Verloop van Woningen tekort (aantal)">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
% rokers &gt; 18 jr.
</div>
<div class="cijfer">
17,8<span class="eenheid"></span>
</div>
<img src="figuren/percent_rokers_18_jr.svg" alt="Verloop van % rokers > 18 jr.">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Gemiddelde wachttijd behandeling ziekenhuis (% langer dan Treeknorm)
</div>
<div class="cijfer">
42,0<span class="eenheid">% langer dan Treeknorm</span>
</div>
<img src="figuren/gemiddelde_wachttijd_behandeling_ziekenhuis_percent_langer_dan_treeknorm.svg" alt="Verloop van Gemiddelde wachttijd behandeling ziekenhuis (% langer dan Treeknorm)">
<div class="oordeel">
<i class="stip s-geen"></i>Goede kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Gezonde levensverwachting (bij geboorte) - mannen
</div>
<div class="cijfer">
64,1<span class="eenheid"></span>
</div>
<img src="figuren/gezonde_levensverwachting_bij_geboorte_mannen.svg" alt="Verloop van Gezonde levensverwachting (bij geboorte) - mannen">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
<div class="kaart">
<div class="thema">
Zorg
</div>
<div class="naam">
Gezonde levensverwachting (bij geboorte) - vrouwen
</div>
<div class="cijfer">
62,0<span class="eenheid"></span>
</div>
<img src="figuren/gezonde_levensverwachting_bij_geboorte_vrouwen.svg" alt="Verloop van Gezonde levensverwachting (bij geboorte) - vrouwen">
<div class="oordeel">
<i class="stip s-geen"></i>Verkeerde kant op
</div>
</div>
</div>
</section>
<section id="waar-het-misgaat" class="level2">
<h2 class="anchored" data-anchor-id="waar-het-misgaat">Waar het misgaat</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 51%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Thema</th>
<th style="text-align: left;">Indicator</th>
<th style="text-align: right;">Nu</th>
<th style="text-align: right;">Streefwaarde</th>
<th style="text-align: right;">Verwacht in doeljaar</th>
<th style="text-align: right;">Per jaar</th>
<th style="text-align: left;">Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">EMU-saldo (% BBP)</td>
<td style="text-align: right;">-1.6</td>
<td style="text-align: right;">-3.0</td>
<td style="text-align: right;">-2.9</td>
<td style="text-align: right;">-0.268</td>
<td style="text-align: left;">Doel gehaald</td>
</tr>
<tr class="even">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Uitgaven ontwikkelingssamenwerking (als % BNI)</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">R en D uitgaven (% BBP)</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">2.5</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Aandeel Natura 2000 dat voldoende onder de Kritische DepositieWaarde (KDW) zit</td>
<td style="text-align: right;">29.9</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">31.3</td>
<td style="text-align: right;">0.209</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Broeikasgasemissies (CO2-eq. Mton)</td>
<td style="text-align: right;">145.6</td>
<td style="text-align: right;">22.7</td>
<td style="text-align: right;">55.1</td>
<td style="text-align: right;">-5.714</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Hernieuwbare energie - eindgebruik (%)</td>
<td style="text-align: right;">20.2</td>
<td style="text-align: right;">39.0</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">2.189</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Stikstofdepositie gevoelige natuurgebieden (mol/ha)</td>
<td style="text-align: right;">1348.0</td>
<td style="text-align: right;">850.0</td>
<td style="text-align: right;">1116.5</td>
<td style="text-align: right;">-18.971</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Dakloosheid (dakloze mensen x 1.000)</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">25.2</td>
<td style="text-align: right;">-0.820</td>
<td style="text-align: left;">Te traag</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Vullingsgraad formatie krijgsmacht (Militair personeel)</td>
<td style="text-align: right;">79.5</td>
<td style="text-align: right;">86.7</td>
<td style="text-align: right;">78.4</td>
<td style="text-align: right;">-0.350</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">Aantallen vroegtijdig schoolverlaters (12-23 jaar)</td>
<td style="text-align: right;">34210.0</td>
<td style="text-align: right;">18000.0</td>
<td style="text-align: right;">41206.0</td>
<td style="text-align: right;">2258.000</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">% rokers 12-18 jr.</td>
<td style="text-align: right;">7.9</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">17.8</td>
<td style="text-align: right;">0.640</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties BMR)</td>
<td style="text-align: right;">88.8</td>
<td style="text-align: right;">95.0</td>
<td style="text-align: right;">82.2</td>
<td style="text-align: right;">-1.191</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties totaal)</td>
<td style="text-align: right;">86.0</td>
<td style="text-align: right;">90.0</td>
<td style="text-align: right;">76.4</td>
<td style="text-align: right;">-1.520</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Voldoende beweging (% bevolking &gt; 4 jr.)</td>
<td style="text-align: right;">47.0</td>
<td style="text-align: right;">75.0</td>
<td style="text-align: right;">31.7</td>
<td style="text-align: right;">-0.877</td>
<td style="text-align: left;">Verkeerde richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">Armoede intensiteit (% inkomenstekort ten opzichte van de armoedegrens bij de mediaan binnen de groep in armoede)</td>
<td style="text-align: right;">19.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">2.500</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">Huishoudens met problematische schulden (%)</td>
<td style="text-align: right;">8.6</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.223</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Aantal geregistreerde misdrijven</td>
<td style="text-align: right;">816.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">5.571</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Aantal opgehelderde misdrijven</td>
<td style="text-align: right;">180.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-5.857</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Ophelderingspercentage misdrijven</td>
<td style="text-align: right;">22.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.907</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Slachtoffers traditionele criminaliteit (% bevolking)</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.725</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Ervaren discriminatie (% personen 15+)</td>
<td style="text-align: right;">12.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.200</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Inkomensongelijkheid (Gini-coëfficiënt)</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Living Planet Index - NL (fauna het land) (1990 = 100)</td>
<td style="text-align: right;">69.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-1.300</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Living Planet Index - NL (fauna zoetwater)</td>
<td style="text-align: right;">159.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-3.900</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">“Rule of Law”-index (rang)</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">0.800</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">“Rule of Law”-index (score)</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.003</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">Vertrouwen in Tweede Kamer (% met (tamelijk) veel vertrouwen)</td>
<td style="text-align: right;">24.6</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-5.069</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Woningen tekort (aantal)</td>
<td style="text-align: right;">396.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">21.886</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Gezonde levensverwachting (bij geboorte) - mannen</td>
<td style="text-align: right;">64.1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.466</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Gezonde levensverwachting (bij geboorte) - vrouwen</td>
<td style="text-align: right;">62.0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.806</td>
<td style="text-align: left;">Alleen richting</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="hoe-hard-zijn-de-doelen" class="level2">
<h2 class="anchored" data-anchor-id="hoe-hard-zijn-de-doelen">Hoe hard zijn de doelen?</h2>
<p>De Rekenkamer noteert per indicator waar het doel op berust: een wet, een verdrag, een Europese afspraak of alleen beleid. Dat onderscheid bepaalt hoeveel gewicht een gemiste norm heeft.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Grondslag</th>
<th style="text-align: right;">Zonder streefwaarde</th>
<th style="text-align: right;">Met streefwaarde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Beleidsafspraak</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Internationale afspraak</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overig</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wet of verdrag</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="bestaanszekerheid" class="level2">
<h2 class="anchored" data-anchor-id="bestaanszekerheid">Bestaanszekerheid</h2>
<p><img src="figuren/thema_bestaanszekerheid.svg" alt="Indicatoren voor Bestaanszekerheid" style="width:100%"> - <strong>% personen onder NL-armoedegrens (nieuwe CBS–SCP–Nibud-methode)</strong> voldoet aan de norm. - <strong>Armoede intensiteit (% inkomenstekort ten opzichte van de armoedegrens bij de mediaan binnen de groep in armoede)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Huishoudens met problematische schulden (%)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Kinderarmoede (% kinderen &lt; 18)</strong> voldoet aan de norm.</p>
</section>
<section id="binnenlandse-veiligheid" class="level2">
<h2 class="anchored" data-anchor-id="binnenlandse-veiligheid">Binnenlandse Veiligheid</h2>
<p><img src="figuren/thema_binnenlandse_veiligheid.svg" alt="Indicatoren voor Binnenlandse Veiligheid" style="width:100%"> - <strong>Aantal geregistreerde misdrijven</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Aantal opgehelderde misdrijven</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>High Impact Crimes x 1.000</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>National Cybersecurity Index - NL (ranking)</strong>: de bron legt geen gewenste richting vast. - <strong>National Cybersecurity Index - NL (score)</strong>: de bron legt geen gewenste richting vast. - <strong>Ophelderingspercentage misdrijven</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Slachtoffers traditionele criminaliteit (% bevolking)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Slachtoffers van moord en doodslag per 100.000 inwoners</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op.</p>
</section>
<section id="defensie-en-ontwikkelingssamenwerking" class="level2">
<h2 class="anchored" data-anchor-id="defensie-en-ontwikkelingssamenwerking">Defensie en Ontwikkelingssamenwerking</h2>
<p><img src="figuren/thema_defensie_en_ontwikkelingssamenwerking.svg" alt="Indicatoren voor Defensie en Ontwikkelingssamenwerking" style="width:100%"> - <strong>Defensie uitgaven (NAVO-norm)</strong> ligt op koers voor 2035. - <strong>Investeringsquote defensie uitgaven (% defensie-uitgaven voor investeringen)</strong> voldoet aan de norm. - <strong>Uitgaven ontwikkelingssamenwerking (als % BNI)</strong> beweegt de goede kant op maar beweegt nauwelijks, te langzaam voor de streefwaarde. - <strong>Vullingsgraad formatie krijgsmacht (Militair personeel)</strong> beweegt van het doel af.</p>
</section>
<section id="economie-arbeidsmarkt" class="level2">
<h2 class="anchored" data-anchor-id="economie-arbeidsmarkt">Economie &amp; Arbeidsmarkt</h2>
<p><img src="figuren/thema_economie_arbeidsmarkt.svg" alt="Indicatoren voor Economie &amp; Arbeidsmarkt" style="width:100%"> - <strong>Arbeidsproductiviteit (toegevoegde waarde per gewerkt uur; index, 2021 = 100)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>BBP reële groei</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Concurrentiekracht (World Competitiveness Ranking); rang NL binnen Europa</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Netto arbeidsparticipatie (% 15-75-jarigen met betaald werk)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>R en D uitgaven (% BBP)</strong> stijgt met 0,02 % BBP per jaar; te langzaam voor de norm van 3. Naast die norm geldt Nederlands doel (2,5% sinds 2011, EZLI). - <strong>Werkloosheid (% werkzoekenden 15-75 jaar die direct beschikbaar zijn als percentage van beroepsbevolking)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op.</p>
</section>
<section id="gelijkheidnon-discriminatie" class="level2">
<h2 class="anchored" data-anchor-id="gelijkheidnon-discriminatie">Gelijkheid/non-discriminatie</h2>
<p><img src="figuren/thema_gelijkheid_non_discriminatie.svg" alt="Indicatoren voor Gelijkheid/non-discriminatie" style="width:100%"> - <strong>Ervaren discriminatie (% personen 15+)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Gender-equality index (rang)</strong>: de bron legt geen gewenste richting vast. - <strong>Gender-equality index (score)</strong>: de bron legt geen gewenste richting vast. - <strong>Inkomensongelijkheid (Gini-coëfficiënt)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Loonkloof man/vrouw (inkomen vrouwen als % van inkomen mannen)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Vermogensongelijkheid (Gini-coëfficiënt)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (mannen)</strong>: de bron legt geen gewenste richting vast. - <strong>Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (vrouwen)</strong>: de bron legt geen gewenste richting vast.</p>
</section>
<section id="kennis-vaardigheden" class="level2">
<h2 class="anchored" data-anchor-id="kennis-vaardigheden">Kennis &amp; Vaardigheden</h2>
<p><img src="figuren/thema_kennis_vaardigheden.svg" alt="Indicatoren voor Kennis &amp; Vaardigheden" style="width:100%"> - <strong>Aantallen vroegtijdig schoolverlaters (12-23 jaar)</strong> beweegt van het doel af. - <strong>Minimaal digitale basisvaardigheden (% personen &gt; 12 jaar)</strong>: de bron legt geen gewenste richting vast. - <strong>PIAAC-scores probleemoplossend vermogen</strong>: de bron legt geen gewenste richting vast. - <strong>PIAAC-scores rekenvaardigheid</strong>: de bron legt geen gewenste richting vast. - <strong>PIAAC-scores taalvaardigheid</strong>: de bron legt geen gewenste richting vast. - <strong>PISA-scores lezen</strong>: de bron legt geen gewenste richting vast. - <strong>PISA-scores science</strong>: de bron legt geen gewenste richting vast. - <strong>PISA-scores wiskunde</strong>: de bron legt geen gewenste richting vast.</p>
</section>
<section id="klimaat-en-milieu" class="level2">
<h2 class="anchored" data-anchor-id="klimaat-en-milieu">Klimaat en Milieu</h2>
<p><img src="figuren/thema_klimaat_en_milieu.svg" alt="Indicatoren voor Klimaat en Milieu" style="width:100%"> - <strong>Aandeel Natura 2000 dat voldoende onder de Kritische DepositieWaarde (KDW) zit</strong> beweegt de goede kant op maar stijgt met 0,21 per jaar, te langzaam voor de streefwaarde. - <strong>Ammoniak-uitstoot (NH3) (industrie)</strong> ligt op koers voor 2035. - <strong>Ammoniak-uitstoot (NH3) (landbouw)</strong> ligt op koers voor 2035. - <strong>Broeikasgasemissies (CO2-eq. Mton)</strong> beweegt de goede kant op maar daalt met 5,71 CO2-eq. Mton per jaar, te langzaam voor de streefwaarde. - <strong>Hernieuwbare energie - eindgebruik (%)</strong> beweegt de goede kant op maar stijgt met 2,19 % per jaar, te langzaam voor de streefwaarde. - <strong>Kwaliteit oppervlaktewater (biologisch) (% van goede kwaliteit))</strong>: de bron legt geen gewenste richting vast. - <strong>Kwaliteit oppervlaktewater (chemisch) (% van voldoende kwaliteit))</strong>: de bron legt geen gewenste richting vast. - <strong>Living Planet Index - NL (fauna het land) (1990 = 100)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Living Planet Index - NL (fauna zoetwater)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>NOx-uistoot (mobiliteit)</strong> ligt op koers voor 2035. - <strong>Stikstofdepositie gevoelige natuurgebieden (mol/ha)</strong> beweegt de goede kant op maar daalt met 18,97 mol/ha per jaar, te langzaam voor de streefwaarde.</p>
</section>
<section id="overheidsfinanciën-openbaar-bestuur" class="level2">
<h2 class="anchored" data-anchor-id="overheidsfinanciën-openbaar-bestuur">Overheidsfinanciën &amp; Openbaar bestuur</h2>
<p><img src="figuren/thema_overheidsfinancien_openbaar_bestuur.svg" alt="Indicatoren voor Overheidsfinanciën &amp; Openbaar bestuur" style="width:100%"> - <strong>“Rule of Law”-index (rang)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>“Rule of Law”-index (score)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>EMU-saldo (% BBP)</strong> voldoet aan de norm. - <strong>EMU-saldo (€ mld)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>EMU-schuld (% BBP)</strong> voldoet aan de norm. - <strong>Totale overheidsuitgaven als % BBP</strong>: de bron legt geen gewenste richting vast. - <strong>Vertrouwen in Tweede Kamer (% met (tamelijk) veel vertrouwen)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op.</p>
</section>
<section id="wonen" class="level2">
<h2 class="anchored" data-anchor-id="wonen">Wonen</h2>
<p><img src="figuren/thema_wonen.svg" alt="Indicatoren voor Wonen" style="width:100%"> - <strong>(Mediane) Woonquote (eigenaar)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>(Mediane) Woonquote (huurder)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Dakloosheid (dakloze mensen x 1.000)</strong> beweegt de goede kant op maar daalt met 0,82 dakloze mensen x 1.000 per jaar, te langzaam voor de streefwaarde. - <strong>Verdeling woningvoorraad naar eigendom (koop)</strong>: de bron legt geen gewenste richting vast. - <strong>Verdeling woningvoorraad naar eigendom (sociale huur)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Verdeling woningvoorraad naar eigendom (vrije sectorhuur)</strong>: de bron legt geen gewenste richting vast. - <strong>Woningen tekort (aantal)</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op.</p>
</section>
<section id="zorg" class="level2">
<h2 class="anchored" data-anchor-id="zorg">Zorg</h2>
<p><img src="figuren/thema_zorg.svg" alt="Indicatoren voor Zorg" style="width:100%"> - <strong>% rokers 12-18 jr.</strong> beweegt van het doel af. - <strong>% rokers &gt; 18 jr.</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Gemiddelde wachttijd behandeling ziekenhuis (% langer dan Treeknorm)</strong> heeft geen streefwaarde; de reeks beweegt de goede kant op. - <strong>Gezonde levensverwachting (bij geboorte) - mannen</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Gezonde levensverwachting (bij geboorte) - vrouwen</strong> heeft geen streefwaarde; de reeks beweegt de verkeerde kant op. - <strong>Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties BMR)</strong> beweegt van het doel af. - <strong>Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties totaal)</strong> beweegt van het doel af. - <strong>Voldoende beweging (% bevolking &gt; 4 jr.)</strong> beweegt van het doel af.</p>
</section>
<section id="alle-indicatoren" class="level2">
<h2 class="anchored" data-anchor-id="alle-indicatoren">Alle indicatoren</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 3%">
<col style="width: 0%">
<col style="width: 2%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Thema</th>
<th style="text-align: left;">Indicator</th>
<th style="text-align: left;">Periode</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Laatste</th>
<th style="text-align: left;">Eenheid</th>
<th style="text-align: left;">Doel volgens bron</th>
<th style="text-align: left;">Status</th>
<th style="text-align: left;">Bron</th>
<th style="text-align: left;">Reeks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">% personen onder NL-armoedegrens (nieuwe CBS–SCP–Nibud-methode)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Niet hoger dan 2024: 3,1%</td>
<td style="text-align: left;">Doel gehaald</td>
<td style="text-align: left;">CBS/SCP/Nibud</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">Armoede intensiteit (% inkomenstekort ten opzichte van de armoedegrens bij de mediaan binnen de groep in armoede)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Lager is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/SCP/Nibud</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">Huishoudens met problematische schulden (%)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8.60</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Hoe minder hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bestaanszekerheid</td>
<td style="text-align: left;">Kinderarmoede (% kinderen &lt; 18)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2.80</td>
<td style="text-align: left;">% kinderen &lt; 18</td>
<td style="text-align: left;">Niet hoger dan 2024: 2,8%</td>
<td style="text-align: left;">Doel gehaald</td>
<td style="text-align: left;">CBS/CPB</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Aantal geregistreerde misdrijven</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">816.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Lager # is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/Politie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Aantal opgehelderde misdrijven</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">180.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Meer opgehelderd is beter (hoger aantal)</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/Politie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">High Impact Crimes x 1.000</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">103.73</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Hoe minder hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">National Cybersecurity Index - NL (ranking)</td>
<td style="text-align: left;">2022–2024</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">35.00</td>
<td style="text-align: left;">ranking</td>
<td style="text-align: left;">hoe lager het cijfer van de ranking, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">e-Governance Academy (Estland)</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">National Cybersecurity Index - NL (score)</td>
<td style="text-align: left;">2022–2024</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">81.67</td>
<td style="text-align: left;">score</td>
<td style="text-align: left;">Hoe hoger, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">e-Governance Academy (Estland)</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Ophelderingspercentage misdrijven</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">22.05</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">hoger % opgehelderd is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/Politie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Slachtoffers traditionele criminaliteit (% bevolking)</td>
<td style="text-align: left;">2021–2025</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">20.00</td>
<td style="text-align: left;">% bevolking</td>
<td style="text-align: left;">Hoe minder hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Binnenlandse Veiligheid</td>
<td style="text-align: left;">Slachtoffers van moord en doodslag per 100.000 inwoners</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Hoe minder hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Defensie uitgaven (NAVO-norm)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2.22</td>
<td style="text-align: left;">NAVO-norm</td>
<td style="text-align: left;">2035: 3,5% BBP</td>
<td style="text-align: left;">Op koers</td>
<td style="text-align: left;">Defensie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Investeringsquote defensie uitgaven (% defensie-uitgaven voor investeringen)</td>
<td style="text-align: left;">2022–2025</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">30.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">&gt; 20%</td>
<td style="text-align: left;">Doel gehaald</td>
<td style="text-align: left;">Defensie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Uitgaven ontwikkelingssamenwerking (als % BNI)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.54</td>
<td style="text-align: left;">als % BNI</td>
<td style="text-align: left;">0,007</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Defensie en Ontwikkelingssamenwerking</td>
<td style="text-align: left;">Vullingsgraad formatie krijgsmacht (Militair personeel)</td>
<td style="text-align: left;">2021–2025</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">79.50</td>
<td style="text-align: left;">Militair personeel</td>
<td style="text-align: left;">2025: 86,7%</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">Defensie</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">Arbeidsproductiviteit (toegevoegde waarde per gewerkt uur; index, 2021 = 100)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">99.90</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere indexscore is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">BBP reële groei</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">Concurrentiekracht (World Competitiveness Ranking); rang NL binnen Europa</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Hogere rang is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">IMD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">Netto arbeidsparticipatie (% 15-75-jarigen met betaald werk)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">73.20</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hoger % is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">R en D uitgaven (% BBP)</td>
<td style="text-align: left;">2013–2024</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">2.36</td>
<td style="text-align: left;">% BBP</td>
<td style="text-align: left;">0.03</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">CBS StatLine 84644NED</td>
<td style="text-align: left;">CBS</td>
</tr>
<tr class="even">
<td style="text-align: left;">Economie &amp; Arbeidsmarkt</td>
<td style="text-align: left;">Werkloosheid (% werkzoekenden 15-75 jaar die direct beschikbaar zijn als percentage van beroepsbevolking)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">3.90</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een lager % is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Ervaren discriminatie (% personen 15+)</td>
<td style="text-align: left;">2021–2025</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: left;">% personen 15+</td>
<td style="text-align: left;">Hoe lager, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS Veiligheidsmonitor</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Gender-equality index (rang)</td>
<td style="text-align: left;">2025–2025</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.00</td>
<td style="text-align: left;">rang</td>
<td style="text-align: left;">Een hogere positie (lager getal) is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">EIGE</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Gender-equality index (score)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">69.50</td>
<td style="text-align: left;">score</td>
<td style="text-align: left;">Hoe hoger, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">EIGE</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Inkomensongelijkheid (Gini-coëfficiënt)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: left;">Gini-coëfficiënt</td>
<td style="text-align: left;">Hoe lager, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Loonkloof man/vrouw (inkomen vrouwen als % van inkomen mannen)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">90.30</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Een hoger % is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Vermogensongelijkheid (Gini-coëfficiënt)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: left;">Gini-coëfficiënt</td>
<td style="text-align: left;">Hoe lager, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (mannen)</td>
<td style="text-align: left;">2020–2022</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">20.80</td>
<td style="text-align: left;">mannen</td>
<td style="text-align: left;">Hoe lager/kleiner, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gelijkheid/non-discriminatie</td>
<td style="text-align: left;">Verschil (in jaren) gezonde levensverwachting tussen hoogste en laagste inkomenskwintiel (vrouwen)</td>
<td style="text-align: left;">2020–2022</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">21.70</td>
<td style="text-align: left;">vrouwen</td>
<td style="text-align: left;">Hoe lager/kleiner, hoe beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">Aantallen vroegtijdig schoolverlaters (12-23 jaar)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">34210.00</td>
<td style="text-align: left;">12-23 jaar</td>
<td style="text-align: left;">Maximum 2026: 18.000</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">Minimaal digitale basisvaardigheden (% personen &gt; 12 jaar)</td>
<td style="text-align: left;">2021–2023</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">78.70</td>
<td style="text-align: left;">% personen &gt; 12 jaar</td>
<td style="text-align: left;">Doel 2030: 80%</td>
<td style="text-align: left;">Te weinig data</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PIAAC-scores probleemoplossend vermogen</td>
<td style="text-align: left;">2012–2023</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">265.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PIAAC-scores rekenvaardigheid</td>
<td style="text-align: left;">2012–2023</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">284.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PIAAC-scores taalvaardigheid</td>
<td style="text-align: left;">2012–2023</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">279.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PISA-scores lezen</td>
<td style="text-align: left;">2018–2022</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">459.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PISA-scores science</td>
<td style="text-align: left;">2018–2022</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">488.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kennis &amp; Vaardigheden</td>
<td style="text-align: left;">PISA-scores wiskunde</td>
<td style="text-align: left;">2018–2022</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">493.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">OECD</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Aandeel Natura 2000 dat voldoende onder de Kritische DepositieWaarde (KDW) zit</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">29.90</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Doel 2030: 50%; 2035: 74%</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">RIVM/PBL/CLO</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Ammoniak-uitstoot (NH3) (industrie)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1.05</td>
<td style="text-align: left;">industrie</td>
<td style="text-align: left;">2035: 0,7</td>
<td style="text-align: left;">Op koers</td>
<td style="text-align: left;">RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Ammoniak-uitstoot (NH3) (landbouw)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">94.91</td>
<td style="text-align: left;">landbouw</td>
<td style="text-align: left;">2035: 62,6 (42%)</td>
<td style="text-align: left;">Op koers</td>
<td style="text-align: left;">RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Broeikasgasemissies (CO2-eq. Mton)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">145.60</td>
<td style="text-align: left;">CO2-eq. Mton</td>
<td style="text-align: left;">2040: -90% t.o.v. 1990 = 22,7</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Hernieuwbare energie - eindgebruik (%)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">20.18</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Doel 2030: 39%</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Kwaliteit oppervlaktewater (biologisch) (% van goede kwaliteit))</td>
<td style="text-align: left;">2021–2024</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.63</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Doel 2027: 100%</td>
<td style="text-align: left;">Te weinig data</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Kwaliteit oppervlaktewater (chemisch) (% van voldoende kwaliteit))</td>
<td style="text-align: left;">2021–2024</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Doel 2027: 100%</td>
<td style="text-align: left;">Te weinig data</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Living Planet Index - NL (fauna het land) (1990 = 100)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">69.00</td>
<td style="text-align: left;">1990 = 100</td>
<td style="text-align: left;">een hoger indexgetal is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Living Planet Index - NL (fauna zoetwater)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">159.00</td>
<td style="text-align: left;">fauna zoetwater</td>
<td style="text-align: left;">een hoger indexgetal is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">NOx-uistoot (mobiliteit)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">122.41</td>
<td style="text-align: left;">mobiliteit</td>
<td style="text-align: left;">2035: 80,6</td>
<td style="text-align: left;">Op koers</td>
<td style="text-align: left;">RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Klimaat en Milieu</td>
<td style="text-align: left;">Stikstofdepositie gevoelige natuurgebieden (mol/ha)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1348.00</td>
<td style="text-align: left;">mol/ha</td>
<td style="text-align: left;">Doel 2035: 850 mol/ha</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">“Rule of Law”-index (rang)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: left;">rang</td>
<td style="text-align: left;">een lagere rang (getal) is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">World Justice Project</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">“Rule of Law”-index (score)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: left;">score</td>
<td style="text-align: left;">een hogere score is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">World Justice Project</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">EMU-saldo (% BBP)</td>
<td style="text-align: left;">1995–2025</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">-1.60</td>
<td style="text-align: left;">% BBP</td>
<td style="text-align: left;">niet lager dan -3%</td>
<td style="text-align: left;">Doel gehaald</td>
<td style="text-align: left;">CBS StatLine 84118NED</td>
<td style="text-align: left;">CBS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">EMU-saldo (€ mld)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-18.70</td>
<td style="text-align: left;">€ mld</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">EMU-schuld (% BBP)</td>
<td style="text-align: left;">1995–2025</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">44.70</td>
<td style="text-align: left;">% BBP</td>
<td style="text-align: left;">max. 60%</td>
<td style="text-align: left;">Doel gehaald</td>
<td style="text-align: left;">CBS StatLine 84118NED</td>
<td style="text-align: left;">CBS</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">Totale overheidsuitgaven als % BBP</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">44.90</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Geen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Overheidsfinanciën &amp; Openbaar bestuur</td>
<td style="text-align: left;">Vertrouwen in Tweede Kamer (% met (tamelijk) veel vertrouwen)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">24.60</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hoger % is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">(Mediane) Woonquote (eigenaar)</td>
<td style="text-align: left;">2020–2023</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">17.10</td>
<td style="text-align: left;">eigenaar</td>
<td style="text-align: left;">Lager is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">(Mediane) Woonquote (huurder)</td>
<td style="text-align: left;">2020–2023</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">26.40</td>
<td style="text-align: left;">huurder</td>
<td style="text-align: left;">Lager is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Dakloosheid (dakloze mensen x 1.000)</td>
<td style="text-align: left;">2020–2024</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">33.00</td>
<td style="text-align: left;">dakloze mensen x 1.000</td>
<td style="text-align: left;">2030: nul daklozen</td>
<td style="text-align: left;">Te traag</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Verdeling woningvoorraad naar eigendom (koop)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">4754.00</td>
<td style="text-align: left;">koop</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Geen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Verdeling woningvoorraad naar eigendom (sociale huur)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2332.00</td>
<td style="text-align: left;">sociale huur</td>
<td style="text-align: left;">Meer is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Verdeling woningvoorraad naar eigendom (vrije sectorhuur)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1181.00</td>
<td style="text-align: left;">vrije sectorhuur</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Geen richting</td>
<td style="text-align: left;">CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wonen</td>
<td style="text-align: left;">Woningen tekort (aantal)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">396.00</td>
<td style="text-align: left;">aantal</td>
<td style="text-align: left;">Lager tekort is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">CBS/SBF</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">% rokers 12-18 jr.</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7.90</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2040: 0% (12-25jr.)</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">RIVM/CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">% rokers &gt; 18 jr.</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">17.80</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Gemiddelde wachttijd behandeling ziekenhuis (% langer dan Treeknorm)</td>
<td style="text-align: left;">2022–2025</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">42.00</td>
<td style="text-align: left;">% langer dan Treeknorm</td>
<td style="text-align: left;">een lager % is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">Nza</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Gezonde levensverwachting (bij geboorte) - mannen</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">64.10</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere leeftijd is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">RIVM/CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Gezonde levensverwachting (bij geboorte) - vrouwen</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">62.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">een hogere leeftijd is beter</td>
<td style="text-align: left;">Alleen richting</td>
<td style="text-align: left;">RIVM/CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties BMR)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">88.80</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Minimaal 95%</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Vaccinatiegraad Rijksvaccinatieprogramma zuigelingen (geregistreerde vaccinaties totaal)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">86.00</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">Minimaal 90%</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">RIVM</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zorg</td>
<td style="text-align: left;">Voldoende beweging (% bevolking &gt; 4 jr.)</td>
<td style="text-align: left;">2020–2025</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">47.00</td>
<td style="text-align: left;">% bevolking &gt; 4 jr.</td>
<td style="text-align: left;">2040: minimaal 75% (4-17 jr.)</td>
<td style="text-align: left;">Verkeerde richting</td>
<td style="text-align: left;">RIVM/CBS</td>
<td style="text-align: left;">Rekenkamer</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="bronnoot">
<p>Cijfers uit de dataset <em>Blik op Nederland: Dashboard Doelen en Resultaten</em> van de Algemene Rekenkamer, beschikbaar onder CC0 1.0 Universal. De bron bevat metingen voor 2012, 2018 en 2020 tot en met 2025; de mediane indicator heeft vijf metingen. Voor enkele indicatoren is de reeks verlengd met CBS StatLine; die zijn gemarkeerd met “CBS-reeks” en lopen verder terug. Waar beide bronnen een jaar bevatten, is het CBS-cijfer aangehouden, omdat CBS herzieningen doorvoert die de Rekenkamer-publicatie nog niet bevat. Trends zijn lineaire schattingen over de laatste tien jaar en zijn een doorrekening van het verleden, geen prognose. Er wordt bewust geen jaartal genoemd waarop een doel bereikt zou worden: bij een vrijwel vlakke reeks levert die berekening een willekeurig ver jaartal op. In plaats daarvan staat de verandering per jaar vermeld. Ramingen komen uit de concept-Macro Economische Verkenning 2027 van het CPB (14 augustus 2026) en zijn als groene stippellijn weergegeven; een raming is beleidsafhankelijk en wordt periodiek bijgesteld. De streefwaarden zijn afgeleid uit de vrije tekst van de bron en waar nodig handmatig aangevuld; die interpretatie is van de makers van deze pagina, niet van de Algemene Rekenkamer.</p>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Gekopieerd!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Gekopieerd!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>